[build]
  command = "npm run build"
  publish = "dist"

# Serve the thank-you page as a real static file
[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

# SPA fallback for everything else
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
